# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3ea628e2a2d752a85207f49f1ceebf6ea6af785f20ed091487daa437521a99710d3517c303f1ef13b54bd680117249e866ddfaf5132259f9fcf20cf9db59b88

test:
  secret_key_base: 7d0589d29739ebb51a77149b9a09301f30cf562cba1c9a1b46c8865b7f39e875588af207597c41f3c5f24fcc923633d4afb83c45e338b502c931b9d6aa022e10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
